### ISSUE TITLE
Including vendor javascript in files

### ISSUE THREAD

**Issue by karneaud** [MozaikAgency/wp-theme-bootstrap#127]
Hey,

Looking into the web pack thing but for now I just want to include query plugin files into my project. How do I get the into the build?

**Comment by Maximilianos** [comment]
It can depend on the plugin, 
some will export a CommonJS/ES6 module that you can use directly using webpack eg: 

``` javascript
// ./some-module.js
import Masonry from 'masonry-layout';

new Masonry($('[data-amazo-grid]')[0], { ...options });
```

but most jQuery plugins don't do this. With these I tend to `import` them once right after the webpack public path import in the theme's `main.js` file, but you should be able to also import them at the top of the module where you are using them, eg:

``` javascript
// ./some-module.js
import 'slick-carousel';

$('[data-epic-slider]').slick({ ...options });
```
