### ISSUE TITLE
Warnings when installing

### ISSUE THREAD

**Issue by karneaud** [MozaikAgency/wp-theme-bootstrap#146]
Again,

GREAT stuff here. Just a note on it....go these **WARNINGS** when I `npm install`

> deprecated gulp-minify-css@1.2.1: Please use gulp-cssnano instead.
> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to nam
> npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

I upgraded to gulp-cssnano

**Comment by Maximilianos** [comment]
Thanks I've seen these as well. Going to address soon :)

**Comment by Maximilianos** [comment]
Updated all packages to latest in latest release and removed deprecated packages. Warnings still appear when `npm install`ing but these are from package internals.
