### ISSUE TITLE
copying external files to build theme

### ISSUE THREAD

**Issue by karneaud** [MozaikAgency/wp-theme-bootstrap#147]
Is there a way that I can import/ include bower_components files into the assets on build so as to be able to update the file via bower?

e.g

if i use bower_components/jsplugin/files/example.js and bower_components/jsplugin/files/example.css
rather than bundle it into my core files I can include them in the dynamic build to copy over to the dest theme build?

**Comment by Maximilianos** [comment]
In JavaScript doing the following will work:
`bower install jquery` and then in your `main.js` for example: 

``` javascript
// ./assets/js/main.js
import $ from 'jquery'; // this is coming from bower now
// ... rest of code 
```

In your scss its slightly less supported but you could do the following:

``` scss
// ./assets/scss/main.scss
// ... where the vendor stuff goes
@import "../../bower_components/jsplugin/files/example.scss";
// NOTE: do not @import css files in your scss because it does
// not parse them, it just does a regular css @import which is 
// not what you want.

// ... rest of styles
```

If the plugin only comes with `css` and no `scss`, unfortunately what I have been doing is to copy the plugins css into the `assets/scss/vendor/` directory, rename it to an `scss` file (eg. from `example.css` to `example.scss`) and then `@import` it from there in my `main.scss`. I know this makes it slightly more annoying keeping the plugin up to date, but it hasn't been a real issue for us yet.

Now, you also said:

> rather than bundle it into my core files I can include them in the dynamic build to copy over to the dest theme build

I would always advise you to bundle the app; if your project is becoming too big you can either manually split your js/scss files into smaller chunks by adding them separately to the root `js` or `scss` directories: for example: 

```
assets
  - js
    ...
    - main.js // => compiled main.js
    - example.js // => compiled example.js
  - scss
    ...
    - main.scss // => compiled main.css
    - lt-ie9.scss // => compiled lt-ie9.css
```

or for js you can use webpack's excellent code splitting feature: for example:

``` javascript
// ./assets/js/main.js
// ... other code and imports

if (theMapElementExists) {
  require.ensure(['./scripts/map'], require => {
    require('./scripts/map');
    // `./scripts/map` and all its dependencies will be bundled
    // separately from the main.js bundle and will only be downloaded
    // if `theMapElementExists` is true
  });
}
```

Back to what you asked for though. If you want to actually copy over files from the dev theme to the built theme outside of what is currently being done by the build process you will need to add that functionality to the build process yourself.

Check out the fonts gulptask in `gulpfile.js`, `./gulp/core/config/fonts.js` and `./gulp/core/recipes/fonts`. It is the simplest gulp task in the build process and should give you a starting point to do what you want.
