### ISSUE TITLE
Using normal JS syntax

### ISSUE THREAD

**Issue by karneaud** [MozaikAgency/wp-theme-bootstrap#148]
Hello,

Been trying to read up on the Babel/ Webpack principles for the kit and was wondering if there was anyway I can not use the web pack and babel form of using javascript as I'm not proficient in the particular flavour

I'm trying to do a simple jQuery document on load in the main.js file an getting this error

> ERROR in ./assets/js/main.js
>   13:20  warning  Missing function expression name  fund-names

is there a way for me to just use regular javascript ?

**Comment by stelioschar** [comment]
Hey @karneaud,

This is a eslint warning, about the fund-names rule. You can see more about it [here](http://eslint.org/docs/rules/func-names.html)

Wp-theme-starter uses the [airbnb's eslint configuration](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

If you feel that this is frustrating you can change the settings of the es-linter in the [.eslintrc](https://github.com/MozaikAgency/wp-theme-starter/blob/master/.eslintrc) file.
