### ISSUE TITLE
Webpack is missing Bower Plugin on production build

### ISSUE THREAD

**Issue by rogiervanstraten** [MozaikAgency/wp-theme-bootstrap#197]
The Bower Webpack Plugin is missing from the options->webpack->prod->plugins. On watch everything works out just fine. But running **gulp build** will fail the javascript files packing because it cannot resolve bower modules.

The deepMerge function is calling lodash.merge which exactly should be mergeWith.

**Fix:**

``` javascript
/**
 * Simple lodash wrapper to
 * deep merge two objects
 *
 * @param a
 * @param b
 * @returns {*}
 */
module.exports = function (a, b) {
    return lodash.mergeWith(a, b, deep);
};
```

**file location**: ./gulp/core/utils/deepMerge.js

**Comment by Maximilianos** [comment]
yup, thanks for your fix as well #198. merged into master
