### ISSUE TITLE
gulp build not importing nor copying other script files

### ISSUE THREAD

**Issue by goncalomarques** [MozaikAgency/wp-theme-bootstrap#218]
I have two files which I import in main.js and they don't seem to be copied nor bundled on `gulp build`.

The folder structure is:

```
 /js

    main.js

    core.js

    /scripts

          one.js

          two.js`
```

These one.js and two.js don't seem to be imported when I require/import in main.js

Any tips?

**Comment by joseelsantos** [comment]
Just did a fresh install with latest, doesn't even bundle the example file. Haven't had this problem with previous versions...

**Comment by goncalomarques** [comment]
Solved.

Fixed it by updating lodash to 4.1.6 and replacing 

> merge

for 

> mergeWith 

on /gulp/core/utils/deepMerge.js:13

Gonna leave it open until it's fixed or you close it.

**Comment by Maximilianos** [comment]
Hey thanks, that was fixed :) check out: 
- https://github.com/MozaikAgency/wp-theme-starter/pull/198
- https://github.com/MozaikAgency/wp-theme-starter/blob/master/gulp/core/utils/deepMerge.js#L13

**Comment by goncalomarques** [comment]
@Maximilianos That's what I followed. But the commit and the post forgot to mention that we should update lodash to an earlier release. Thanks!
