### ISSUE TITLE
problem with browser-sync

### ISSUE THREAD

**Issue by trikon** [MozaikAgency/wp-theme-bootstrap#259]
Hi, it seems like a minor trouble of choosing free port for BS server.
Here is log from console, after `gulp` command was runned: 

```
[12:40:01] Starting 'styles:watch'...
[12:40:01] Finished 'styles:watch' after 2.33 ms
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3004
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
```

**Comment by stelioschar** [comment]
You may use another process that uses the port needed (`EADDRINUSE `).

**Comment by trikon** [comment]
yes, but maybe there's a way to check if port is free and use it?

and what you think about dynamically select a needed port(after BS is running) and insert it instead of hardcoded port `:3000` on this [line](https://github.com/MozaikAgency/wp-theme-starter/blob/890208669a3d9ec12aef22641ee8ed7d291d0ee6/gulp/core/templates/browser-sync-snippet.js#L15)

**Comment by Maximilianos** [comment]
might be able to use something like:

``` javascript
// We attempt to use the default port but if it is busy, we offer the user to
// run on a different port. `detect()` Promise resolves to the next free port.
detect(DEFAULT_PORT).then(port => {
  if (port === DEFAULT_PORT) {
    run(port);
    return;
  }

  clearConsole();
  var question =
    chalk.yellow('Something is already running at port ' + DEFAULT_PORT + '.') +
    '\n\nWould you like to run the app at another port instead?';

  prompt(question, true).then(shouldChangePort => {
    if (shouldChangePort) {
      run(port);
    }
  });
});
```

stolen from: https://github.com/facebookincubator/create-react-app/pull/362/files#diff-1ab6f53c8795042e5d1f961d6e6b75e5R258

Don't have much time to work on this but will try. If you manage to make progress please pr :)

**Comment by Maximilianos** [comment]
That, or allow the user to specify a port in the config files and read it from there

**Comment by Maximilianos** [comment]
specifically `./gulp/core/templates/browser-sync-snippet.js` could read the port the user would want to use from `./gulp/core/config/browser-sync.js`.

And the user could define the port they would like to run browser-sync from in `./gulp/config/browser-sync.js` with something like the following:

``` javascript
/**
 * Override the Default
 * Core Browser Sync
 * Config
 *
 */
module.exports = {
  port: 8080
};
```

**Comment by Maximilianos** [comment]
implemented aforementioned fix

@trikon plz check https://github.com/MozaikAgency/wp-theme-starter/pull/260
and see if it works for you

**Comment by trikon** [comment]
yes, it is good idea to choose needed port in `./gulp/config/browser-sync.js` file. And i's works fine for me, thanks.
But i think it would be a great to choose free port automatically. and if it choosen by BS insert it [here](https://github.com/MozaikAgency/wp-theme-starter/blob/890208669a3d9ec12aef22641ee8ed7d291d0ee6/gulp/core/templates/browser-sync-snippet.js#L15)
What you think?

**Comment by Maximilianos** [comment]
The EADDRINUSE error has been good for us letting us know that we've already got an instance of gulp running for the current project, so I am still not sure about the pros and cons yet.

I understand your thinking, still not sure if it is worth it to add this feature to the build process when you can manage it now since #260 . And I imagine that the detecting stuff may turn out to be relatively complex to implement so will need extra investigation. I'm going to merge the fix into master and close this issue but will think about how the other feature could work. 

Thanks for the contribution :)
