### ISSUE TITLE
Disable eslint

### ISSUE THREAD

**Issue by PascalAOMS** [MozaikAgency/wp-theme-bootstrap#264]
How does one disable eslint?
I'm using a different system so I don't need it.

After I deleted the packages and the configuration, it threw errors that webpack stream still needs it.
I'm a bit confused here.

**Comment by torrfura** [comment]
Why would you do that? It's a really good help keeping your code clean. 
If you like to disable eslint for a specific .js file, just add `/* eslint-disable */` at the top of the file.

**Comment by PascalAOMS** [comment]
It is a great help but I use Atom with linter plugins which have a better interface than what the terminal can offer. :)

**Comment by Maximilianos** [comment]
Hey @PascalAOMS can you try updating babel to 6.14.0 and disabling eslint then? Let me know if that helps.

**Comment by PascalAOMS** [comment]
Updated Babel, no change.

After deleting the eslint packages, eslint comments in my js files and running gulp it says:

```
Error in plugin 'webpack-stream'
Message:
multi core
Module not found: Error: Cannot resolve module 'eslint'
```

The rest renders fine and I could still work normally.

If I don't delete the eslint packages, the only error it throws is not finding the config file.

**Comment by PascalAOMS** [comment]
Can be closed.
Simply missed one eslint comment in a webpack configuration file. Was well hidden. 😄 

Sorry for the inconvenience and thanks for the help.

**Comment by Maximilianos** [comment]
No worries, the config overriding could possibly be done differently to make this sort of thing easier.. but I don't know exactly what the better way of doing it would be. Glad you got it working :)
