### ISSUE TITLE
Fonts not being copied properly in default build script?

### ISSUE THREAD

**Issue by harrisonfm** [MozaikAgency/wp-theme-bootstrap#269]
I added some fonts from icomoon in dev/assets/scss/fonts, but don't see a fonts folder being copied to prod/assets/. I've made no modifications to the fonts.js part of the default build script, nor the gulpfile.

Manually copy pasting the fonts folder to prod, however, works, so I'm concluding that this isn't a path error or anything on my end.

**Comment by Maximilianos** [comment]
Hey @harrisonfm, the default gulp setup looks for the fonts in `./assets/fonts/` not `./assets/scss/fonts/`. You can see that in this file: https://github.com/MozaikAgency/wp-theme-starter/blob/master/gulp/core/config/fonts.js.

If you want to change where gulp looks for the fonts you can change the `./gulp/config/fonts.js` file to something like the following:

``` javascript
var assets = require('../core/config/common').paths.assets;

/**
 * Override the Default
 * Core Fonts
 * Config
 *
 */
module.exports = {
    paths: {
        watch: assets.src  + '/scss/fonts/**/*.{eot,otf,ttf,woff,woff2,svg}',
        src:   assets.src  + '/scss/fonts/**/*.{eot,otf,ttf,woff,woff2,svg}',
        dest:  assets.dest + '/scss/fonts',
        clean: assets.dest + '/scss/fonts/**/*.{eot,otf,ttf,woff,woff2,svg}'
    }
};
```

The idea for the default setup is that font files live in the `./assets/fonts` directory, but the scss `@font-face` stuff on how the fonts are being loaded/use live in the `./assets/scss/fonts/` directory.

**Comment by harrisonfm** [comment]
I see now. I wrongly assumed where fonts were supposed to live. I moved everything to /assets/fonts and it works fine there, no need to modify the build script.

I really appreciate the quick and thorough response, really liking this boilerplate.
