### ISSUE TITLE
Scripts in 'vendor' folder are missing in the final built theme

### ISSUE THREAD

**Issue by gopalraju** [MozaikAgency/wp-theme-bootstrap#270]

**Comment by Maximilianos** [comment]
Hey @gopalraju, 'vendor' scripts do not get automatically transferred into the built theme. You will need to require the individual scripts in one of your entry js files, such as `./dev_theme/assets/js/main.js`. Something like the following:

``` javascript
// vendor scripts
import './vendor/path/to/awesome/lib';
import './vendor/path/to/other/awesome/lib';
...

// your scripts
import './scripts/path/to/even/better/custom/script';
...
```

Something like that. The idea is to serve concatenated bundles of javascript. If you want to split the bundle up into smaller packages consider either using multiple entry files, eg`main2.js`, or, even better, using [webpack's code chunking/splitting](https://webpack.github.io/docs/code-splitting.html)

**Comment by gopalraju** [comment]
Thanks Max
