### ISSUE TITLE
Site does not reload when theme files are changed

### ISSUE THREAD

**Issue by tylershuster** [MozaikAgency/wp-theme-bootstrap#29]
I'm under the impression that intended behavior is that the site reloads when any files are changed, either assets or theme files. That's how it's worked on my local machine. However, I've installed this on networked Windows & Ubuntu machines and when I change the SCSS for example, it's injected. When I change one of the theme templates, however, it does not.

It should be noted that the "Reloading Browsers" line appears in the terminal.

No errors appear in the browser console.

**Comment by guidebin** [comment]
I couldn't find it documented either, but you can just modify `./gulp/config/browsersync.js` to get browsersync working, change it to look like this:

``` javascript
module.exports = {
    proxy: "your localhost dev url here"
};
```

Then, go to `localhost:3001` in your browser and there's the autoreloading version of your site.

You can also add `open: true` to the config if you want your browsersync to open the dev server in your default browser after gulp finishes building.

**Comment by randychampagne** [comment]
Thank you for this info. Setting to proxy and files properties for browser-sync solved the problem for me ^_^.
