### ISSUE TITLE
Python not mentioned as a prerequisite

### ISSUE THREAD

**Issue by AlexGustafsson** [MozaikAgency/wp-theme-bootstrap#77]
Multiple modules rely on Python (at least on my Windows installation). This requirement is not expressed in the documentation, but it should be.

It took me a while to figure out why the build actions were not working and indeed, it was the lack of Python.

Python should probably go as a documented prerequisite since npm won't install it for you.

**Comment by Maximilianos** [comment]
Hey Alex,
Was it a `libsass/node-sass/gulp-sass` related issue that required Python, do you remember?
Or were there other modules also involved?

**Comment by Maximilianos** [comment]
Added note to README to highlight potential pain points for Windows users.
